## Search for   "change here"   before running!

In [1]:
import pandas as pd

In [ ]:
# change here
points_to_ingore = [
	"16", "17", "18", "19", "20", 
	"21", "22", "23", "24", "25", 
	"26", "27", "32", "33", "34", 
	"37", "38", "39", "40", "41", 
	"42", "46", "47", "48", "49", 
	"50", "51"
	]

In [15]:
num_total_points = 51
num_ignored_points = len(points_to_ingore)
num_remaining_points = num_total_points - num_ignored_points
print("number of total points: ", num_total_points)
print("number of ignored points: ", num_ignored_points)
print("number of remaining points: ", num_remaining_points)

number of total points:  51
number of ignored points:  27
number of remaining points:  24

In [ ]:
file_path = "../configurations/51-points/CollectedData_furkan.csv" # may change here

# total 195 rows, equal to number of labeled images
df = pd.read_csv(file_path, header=[0, 1, 2], index_col=[0, 1, 2])  
df.head()

scorer                                furkan                          \
bodyparts                                  1                       2
coords                                     x           y           x
labeled-data video 1001_10.l.png  326.562467  244.791583  283.515143
                   1001_10.r.png  319.165367  246.617371  361.020354
                   1053_1.l.png   302.104322  300.373818  254.030880
                   1053_1.r.png   309.566807  297.495587  355.487706
                   1069_2.l.png   354.058620  224.681063  308.616063

scorer                                                                \
bodyparts                                              3
coords                                     y           x           y
labeled-data video 1001_10.l.png  210.589599  356.046936  230.344193
                   1001_10.r.png  208.589126  292.378176  234.658803
                   1053_1.l.png   281.479282  330.087370  285.545195
                   1053_1.r.png   273.578452  281.583758  284.101992
                   1069_2.l.png   196.698015  381.929731  214.828979

scorer                                                                \
bodyparts                                  4                       5
coords                                     x           y           x
labeled-data video 1001_10.l.png  295.603775  179.630906  350.739732
                   1001_10.r.png  344.995873  177.257679  292.856519
                   1053_1.l.png   268.859504  236.515067  322.673058
                   1053_1.r.png   342.094111  231.723465  287.802214
                   1069_2.l.png   323.588845  168.105206  369.675134

scorer                                        ...                           \
bodyparts                                     ...          47
coords                                     y  ...           x            y
labeled-data video 1001_10.l.png  178.451527  ...  398.433851  1468.195432
                   1001_10.r.png  185.628676  ...  252.319569  1464.255883
                   1053_1.l.png   234.601696  ...  352.735507  1450.490505
                   1053_1.r.png   234.354350  ...  272.949674  1446.234466
                   1069_2.l.png   164.423225  ...  387.721800  1461.672649

scorer                                                                 \
bodyparts                                 48                       49
coords                                     x            y           x
labeled-data video 1001_10.l.png  425.497894  1466.791165  417.710598
                   1001_10.r.png  223.606026  1462.315779  232.530505
                   1053_1.l.png   376.097394  1447.043669  368.310098
                   1053_1.r.png   249.028379  1443.852692  257.002144
                   1069_2.l.png   409.934741  1459.885401  403.424052

scorer                                                                  \
bodyparts                                              50
coords                                      y           x            y
labeled-data video 1001_10.l.png  1468.706074  379.412424  1478.280618
                   1001_10.r.png  1464.061872  271.138580  1475.896508
                   1053_1.l.png   1448.192614  337.799219  1459.171424
                   1053_1.r.png   1444.784690  288.897204  1455.865117
                   1069_2.l.png   1461.034346  370.359961  1469.459945

scorer
bodyparts                                 51
coords                                     x            y
labeled-data video 1001_10.l.png  434.178814  1476.238048
                   1001_10.r.png  214.099515  1475.508487
                   1053_1.l.png   384.012350  1454.575643
                   1053_1.r.png   241.365280  1452.551344
                   1069_2.l.png   418.743321  1468.055678

[5 rows x 102 columns]

In [17]:
new_df = df.drop(columns=points_to_ingore, level='bodyparts')
new_df.head()

scorer                                furkan                          \
bodyparts                                  1                       2
coords                                     x           y           x
labeled-data video 1001_10.l.png  326.562467  244.791583  283.515143
                   1001_10.r.png  319.165367  246.617371  361.020354
                   1053_1.l.png   302.104322  300.373818  254.030880
                   1053_1.r.png   309.566807  297.495587  355.487706
                   1069_2.l.png   354.058620  224.681063  308.616063

scorer                                                                \
bodyparts                                              3
coords                                     y           x           y
labeled-data video 1001_10.l.png  210.589599  356.046936  230.344193
                   1001_10.r.png  208.589126  292.378176  234.658803
                   1053_1.l.png   281.479282  330.087370  285.545195
                   1053_1.r.png   273.578452  281.583758  284.101992
                   1069_2.l.png   196.698015  381.929731  214.828979

scorer                                                                \
bodyparts                                  4                       5
coords                                     x           y           x
labeled-data video 1001_10.l.png  295.603775  179.630906  350.739732
                   1001_10.r.png  344.995873  177.257679  292.856519
                   1053_1.l.png   268.859504  236.515067  322.673058
                   1053_1.r.png   342.094111  231.723465  287.802214
                   1069_2.l.png   323.588845  168.105206  369.675134

scorer                                        ...                          \
bodyparts                                     ...          35
coords                                     y  ...           x           y
labeled-data video 1001_10.l.png  178.451527  ...  292.479502  941.094173
                   1001_10.r.png  185.628676  ...  366.151046  928.078249
                   1053_1.l.png   234.601696  ...  265.912727  977.614622
                   1053_1.r.png   234.354350  ...  350.328877  982.763312
                   1069_2.l.png   164.423225  ...  316.281880  899.276742

scorer                                                                \
bodyparts                                 36                      43
coords                                     x           y           x
labeled-data video 1001_10.l.png  400.737319  933.915787  381.837975
                   1001_10.r.png  250.951164  927.133988  266.482330
                   1053_1.l.png   367.263442  971.949054  338.182201
                   1053_1.r.png   249.831477  971.316697  286.411875
                   1069_2.l.png   429.593239  912.496400  373.679136

scorer                                                                  \
bodyparts                                              44
coords                                      y           x            y
labeled-data video 1001_10.l.png  1470.620983  430.604317  1468.195432
                   1001_10.r.png  1466.972029  216.427640  1465.807966
                   1053_1.l.png   1452.788395  381.459138  1447.681972
                   1053_1.r.png   1448.719795  242.193723  1446.441576
                   1069_2.l.png   1462.055631  415.807128  1460.906686

scorer
bodyparts                                 45
coords                                     x            y
labeled-data video 1001_10.l.png  408.136055  1468.833735
                   1001_10.r.png  242.619047  1464.255883
                   1053_1.l.png   360.395142  1449.596881
                   1053_1.r.png   265.079464  1445.923799
                   1069_2.l.png   396.147398  1461.162007

[5 rows x 48 columns]

In [ ]:
# change here
new_df.to_csv("../configurations/27-points/CollectedData_furkan.csv")